
title: My Resume
url: 'http://junlulocky.com'
baseurl: dubsCV' #change it according to your repository name
# publishDir: 'dist'



# Profile information
yourname: Christian Walker  ## put your name
title: 'ENTREPRENEUR'  ## your title
location: PA, USA


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/cdwalkers/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
